name: Docker Image CI
 
on:

  push:
    branches: [ development ]
    paths-ignore:
    - ".github/workflows/**"  
  
  workflow_dispatch:

jobs:
   
  build:

    runs-on: master

    steps:
      - uses: actions/checkout@v2     
      -  name: Login to registry
         uses: docker/login-action@v1
         with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PWD }}

    
      - name: Build the Docker image    
        run: | 
             docker build . --file src/SME.Worker.Agendador.Api/Dockerfile --tag ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-worker-agendador
             docker push ${{ secrets.REGISTRY_HOST }}/${GITHUB_REF##*/}/sme-worker-agendador 
